### ISSUE TITLE
Status code 413 for various requests on 32-bit windows builds

### ISSUE THREAD

**Issue by MeijeSibbel** [Storj/libstorj#195]
OS: windows 10
```
C:\Users\Dani Marion\Desktop\storj-1.0.0-beta1\bin>storj add-bucket test
Request failed with status code: 413
Failed to add bucket.

C:\Users\Dani Marion\Desktop\storj-1.0.0-beta1\bin>
```

**Comment by braydonf** [comment]
HTTP code 413 is request entity too large, are you doing something strange here?

**Comment by braydonf** [comment]
Related 413 error: https://github.com/Storj/libstorj/issues/194

**Comment by aleitner** [comment]
Only appears on 32bit windows build of libstorj

**Comment by braydonf** [comment]
Also confirmed this is related to the 32bit windows build, and the 'Content-Length' header is being set incorrectly.
