### ISSUE TITLE
File size is unknown on windows 10

### ISSUE THREAD

**Issue by MeijeSibbel** [Storj/libstorj#198]
OS: windows 10

````
C:\Users\Dani Marion\Desktop\storj-1.0.0-beta1\bin>storj upload-file 727899d0b847fe1c2edde6a5 C:\Users\Dani Marion\Desktop\storj-1.0.0-beta1\bin\storj.exe

Upload failure: File size error

C:\Users\Dani Marion\Desktop\storj-1.0.0-beta1\bin>
```

**Comment by braydonf** [comment]
Can you run the same command but with `storj --debug upload-file ...`

**Comment by MeijeSibbel** [comment]
@braydonf :
```
C:\Users\Dani Marion\Desktop\storj-1.0.0-beta1\bin>storj --debug upload-file 727899d0b847fe1c2edde6a5 C:\Users\Dani Marion\Desktop\storj-1.0.0-beta1\bin\storj.e
xe
{"message": "File size is unknown", "level": 1, "timestamp": 2531410303}

Upload failure: File size error

C:\Users\Dani Marion\Desktop\storj-1.0.0-beta1\bin>
```

**Comment by braydonf** [comment]
Can you try a directory with out a space, perhaps this is related to https://github.com/Storj/libstorj/issues/200#issuecomment-284117820

Any case, there should be a better error message.

**Comment by MeijeSibbel** [comment]
@braydonf :
```
C:\storj\bin>storj upload-file 88ba4d4e75210e1dece9222a C:\storj\bin\storj.exe

Upload failure: Bridge frame request error

C:\storj\bin>

```

**Comment by braydonf** [comment]
Okay, @MeijeSibbel I've created a separate issue regarding that error: https://github.com/Storj/libstorj/issues/206

If you wrap the file path in quotes the space is not split. I get an "Invalid file path: <path>" error when  a file can be found though, not "File size error".

**Comment by braydonf** [comment]
I think this is related to uploading a file with zero bytes, in which case this is the correct error message. If this is not the case we can reopen.
