### ISSUE TITLE
Password blind entry windows cmd

### ISSUE THREAD

**Issue by littleskunk** [Storj/libstorj#201]
I am using a password manager. My cmd codepage is set to utf-8 to accept my password.

The problem is that I get no feedback. I paste my password but I don't see if it is accepted or not. I would expect something like this (old storj-cli) 
` [...]  > Enter your passphrase to unlock your keyring  >  *********`

All I see is this:
```
C:\Users\Skunk\Downloads\Storj CLI\storj-1.0.0-beta1\bin>storj -d list-bucket
Bridge username (email): skunk@storj.io
Bridge password:
Encryption mnemonic key:
```

**Comment by braydonf** [comment]
There are various commands that work this way, e.g. `sudo`. Is this necessary?

**Comment by littleskunk** [comment]
I think for a Windows User some Feedback is required or they will be confused.
