### ISSUE TITLE
Generate new "encryption key" for existing accounts

### ISSUE THREAD

**Issue by littleskunk** [Storj/libstorj#204]
I registered my user some month ago on https://app.storj.io/
It was not generating a Mnemonic key for me. I guess it is still the same but I didn't try it.

Now I have a problem. I can't use `storj register` because I am already registerd but on the other side I can't use `storj import-keys` because I don't have a Mnemonic key.
```
C:\Users\Skunk\Downloads\Storj CLI\storj-1.0.0-beta1\bin>storj import-keys
Would you like to overwrite the current settings?: [y/n] y
Bridge username (email): any@mail.de
Password:
Mnemonic:
Mnemonic integrity check failed.
```

**Comment by littleskunk** [comment]
Workaround:
Use the old cli to generate a mnemonic key.
```
npm install -g storj-cli
storj generate-seed
storj print-seed
```

**Comment by braydonf** [comment]
I think during `import-key` there can be an option to generate a new key if they don't already have one.
