### ISSUE TITLE
Repeated shard challenges

### ISSUE THREAD

**Issue by braydonf** [Storj/libstorj#237]
From chat in community.storj.io, it looks like the shard challenges are repeated on windows, that may or may not be related to large files. See https://community.storj.io/channel/core?msg=zohSeCn3cM2Z6FQW8

**Comment by aleitner** [comment]
Random_buffer must be returning the same buffer every time? https://github.com/Storj/libstorj/blob/master/src/uploader.c#L1240

**Comment by braydonf** [comment]
This may be fixed on master, random_buffer was just updated.

**Comment by braydonf** [comment]
Verified and challenges are not duplicated with latest master at https://github.com/Storj/libstorj/commit/db04370fe8cacc3909866642c34241138cbe5d0d

**Comment by braydonf** [comment]
Confirmed is affecting 32bit windows build

**Comment by braydonf** [comment]
Okay, confirmed that this is an issue with beta2 release on 32bit windows. And has been fixed with beta3.
