### ISSUE TITLE
 False reaching thresholds on free tier

### ISSUE THREAD

**Issue by AlexeyALeonov** [Storj/libstorj#270]
I uploaded many photos to many buckets, but only for 2,9GB (it's showing on the billing page) by storj-cli.
I do not connecting my bank card to Storj account. I want to use the free tier (lesser 25GB).

And now I can't upload the files,  I getting a error:

  Encrypting file "PanoramaGAltajsk_1.jpg"
 [ PanoramaGAltajsk_1.jpg ] Encryption complete
 [ PanoramaGAltajsk_1.jpg ] Storing file, hang tight!
 Creating file staging frame
 Request failed, reason: Could not create frame, transfer rate limit reached. - retrying(false)...

But after 1 hour I can upload this file. The next file getting a same error. After 1 hour I would be able to uploading this file too.

with libstorj I have a same issue.

**Comment by aleitner** [comment]
You are getting rate limited. This is something we added to prevent people from abusing free tier to hose up the network. Additionally failed uploads still count as something added to the rate limit. This is also for protection from malicious attacks. We will add a resume failed/canceled upload/download in the future

**Comment by super3** [comment]
@AlexeyALeonov Reopened. We are looking further into this. Thanks for your patience.

**Comment by barbaraliau** [comment]
User versions:

```
node --version
v6.10.0
```

```
storj --version
Storjcli: 4.0.0 | Core: 6.3.2
```

Additional information: User can only upload a ~2.5MB file per hour, which is still within the free threshold upload limit of 3GB.

**Comment by braydonf** [comment]
If there is an issue w/ incorrect rate limiting being calculated (which I'm fairly sure that there isn't, as there are plenty of tests around it), the issue isn't here, it would be either at the [bridge](https://github.com/storj/bridge) or [service-storage-models](https://github.com/storj/service-storage-models).
