### ISSUE TITLE
Error in Windows Storj Starting

### ISSUE THREAD

**Issue by vkhutal** [Storj/libstorj#290]
![untitled](https://cloud.githubusercontent.com/assets/14245772/25309235/3d500a22-27e5-11e7-94fb-78f2f6352609.png)

**Comment by vkhutal** [comment]
It is happening at start of Storj in Windows

**Comment by braydonf** [comment]
This was fixed in https://github.com/Storj/libstorj/pull/271 and will be in the next release.

Duplicate https://github.com/Storj/libstorj/issues/269
