### ISSUE TITLE
Peer certificate cannot be authenticated with given CA certificates 

### ISSUE THREAD

**Issue by vkhutal** [Storj/libstorj#291]
![storjerror](https://cloud.githubusercontent.com/assets/14245772/25314715/ab2a4f22-2866-11e7-8f80-c3dc93d8dbc7.png)

**Comment by braydonf** [comment]
This should have been resolved with https://github.com/Storj/libstorj/issues/123

**Comment by braydonf** [comment]
What version of OS?

**Comment by vkhutal** [comment]
It was old OS. I tested on Windows 10
