### ISSUE TITLE
Configurable upload opts

### ISSUE THREAD

**Issue by aleitner** [Storj/libstorj#292]
- [x] reed solomon (default: true)
- [x] Push shard limit (default: 64)
- [x] Push frame limit (default: 64)
- [x] Prepare frame limit (default: 1) // Defaults to 1 for HDD

**Comment by Th3Van** [comment]
How about adding `shard size` opt while uploading?

**Comment by braydonf** [comment]
That's probably not something that needs to be configurable as a user option. It may also not be necessary to adjust the other limits, as the thread pool size reflects most of it.
