### ISSUE TITLE
No data is being downloaded yet it writes file to disk 

### ISSUE THREAD

**Issue by MeijeSibbel** [Storj/libstorj#298]
I did some more testing, this is what is going on:

1- start the download
2- Download hangs at 0.02% yet Libstorj is writing to the disc, see images below.
3- Libstorj exits with a error, disk writing stops

Interpretation: Storj is writing the file with random data (zeros?)

![issue](https://cloud.githubusercontent.com/assets/11735738/25407091/f6c7c8c4-2a00-11e7-960e-1ed51216f1b0.png)
![libsttorjc_issue](https://cloud.githubusercontent.com/assets/11735738/25407092/f6c7aa6a-2a00-11e7-9c02-b47ee78976a5.png)

**Comment by MeijeSibbel** [comment]
I did some more testing, this is what is going on:

1- start the upload
2- Upload hangs at 0.02% yet Libstorj is writing to the disc, see image below.
3- Libstorj exits with a error, disk writing stops

Interpretation: Storj is writing the file with random data (zeros?)

**Comment by MeijeSibbel** [comment]
![libstorj issue](https://cloud.githubusercontent.com/assets/11735738/25407552/9ca3652c-2a02-11e7-9679-c8f702632064.png)

**Comment by MeijeSibbel** [comment]
Network usage is also zero so it is writing from within the software

**Comment by MeijeSibbel** [comment]
Extra observation:

When Libstorj stops writing to the disk (after step 2 but before step 3) it suddenly downloads some data for a fraction of a second and then stops: 

![issue123](https://cloud.githubusercontent.com/assets/11735738/25407846/d9404256-2a03-11e7-8909-b929c325752c.png)

**Comment by braydonf** [comment]
While downloading it will write asynchronously to disk at the correct position for each shard. If you're downloading one of the later shards, it will be placed there.

**Comment by braydonf** [comment]
I'm assuming the question is why the file is larger than what's been downloaded.

**Comment by MeijeSibbel** [comment]
@braydonf , nothing has been downloaded, it hangs at 0.02% before it even starts downloading a shard. So it isn't downloading anything but writing to my disk at 10mb/s. What is it writing to disk if no data is coming in?, It almost writes the entire file to the disk.

**Comment by braydonf** [comment]
Perhaps the display is not updating correctly, we've seen this before on windows. The progress bar shows bytes, so if there is any percentage then it has started downloading.

**Comment by MeijeSibbel** [comment]
Nope, there is not data being downloaded, i have 3x network usage monitors and not one indicated that there is data being downloaded.

**Comment by braydonf** [comment]
There have been many changes since the rc2 release, and we'll have rc3 released shortly that will greatly improve the success rates for downloads with erasure encoding. 

In rc2 there are only two places that it will write, and that's after receiving bytes:
- https://github.com/Storj/libstorj/blob/1.0.0/src/http.c#L242
- https://github.com/Storj/libstorj/blob/1.0.0/src/downloader.c#L995

**Comment by MeijeSibbel** [comment]
And if it receives a few KB from the first shard and then writes the data in a loop to the disk?. I see a few small download spikes right when i start the download and before it starts writing to the disk. This should be easy to reproduce at the Storj office, just upload a 40-50GB file with windows and try to download, then monitor what happens.

**Comment by MeijeSibbel** [comment]
Closing this for now until i observe the issue again with the new RS version
