### ISSUE TITLE
Logging not working - Windows

### ISSUE THREAD

**Issue by computeronix** [Storj/libstorj#320]
It appears when using storj.exe -l 1/2/3/4  or even adding -d  that no log file is written to during the process.

This was verified using https://technet.microsoft.com/en-us/sysinternals/processmonitor

**Comment by aleitner** [comment]
try using --log or --debug instead

**Comment by computeronix** [comment]
that didnt work either, no log files posted

**Comment by braydonf** [comment]
What commands?

**Comment by computeronix** [comment]
aww ok let me try with one of those commands /// list-buckets was the command i was trying

**Comment by braydonf** [comment]
Verified that logging is working w/ upload-file and download-file.
