### ISSUE TITLE
Getting more detailed results from function call

### ISSUE THREAD

**Issue by BlackDuck888** [Storj/libstorj#327]
I thought the lib is designed as entry for 3rd party apps. I trying my first steps, uploading, downloading and some other things, all of this working great and smooth.

From my point of view the lib is only designed to serve the cli and nothing else.

To make my problem concrete, if i upload i file i expect the file_id as result, than i can process these information in my app. same to create_bucket function or list_files. All these information are only written to stdout if log level is high enough. 

Right now my workaround is that i use the lib like example code, i had large parts rewritten for my used, but this is not ideal because i have to track you changes to keep it working.

My thoughts are only to include and use the story.h without copy and rewriting functions from downloader.h/c oder other files.

i hope you can understand what i want to say, i am not very familiar with english.

Thx for your great work!

**Comment by braydonf** [comment]
There is a void pointer on every callback that can be used for keeping track of info in third-party applications.

**Comment by phutchins** [comment]
@BlackDuck888 https://github.com/Storj/libstorj/pull/328

**Comment by BlackDuck888** [comment]
@phutchins Thank you.

Same problem with create_bucket, or list_files after triggering function i expect a result to work with.

**Comment by phutchins** [comment]
@BlackDuck888 I'll add ID's for create_bucket and others as separate PR's.

**Comment by braydonf** [comment]
Included in RC5: https://github.com/Storj/libstorj/releases/tag/v1.0.0-rc5
