### ISSUE TITLE
Feature Request : Add nodejs bindings 

### ISSUE THREAD

**Issue by QzSG** [Storj/libstorj#346]
Would benefit and increase performance for nodejs applications running on storj.js too. That way, we can have a single library for multiple developer environments. That way storj.js can focus simply on the nodejs api code without worrying about the backend as it is handled by libstorj

**Comment by braydonf** [comment]
This is planned, bindings will be added as another project though.

**Comment by braydonf** [comment]
In progress at https://github.com/Storj/node-libstorj
