### ISSUE TITLE
storj cli does not work with non-ssl bridge

### ISSUE THREAD

**Issue by onsightit** [Storj/libstorj#348]
Recommended changes to src/cli.c:
```
--- a/src/cli.c
+++ b/src/cli.c
@@ -1124,8 +1124,16 @@ int main(int argc, char **argv)
     // Parse the host, part and proto from the storj bridge url
     char proto[6];
     char host[100];
-    int port = 443;
+    int port = 0;
     sscanf(storj_bridge, "%5[^://]://%99[^:/]:%99d", proto, host, &port);
+    // If no port, use defaults.
+    if (port == 0) {
+        if (!strcmp(proto, "http")) {
+            port = 80;
+        } else {
+            port = 443;
+        }
+    }
```

**Comment by Th3Van** [comment]
As a temporary workaround, you could also use `:80` like this for non-ssl bridge : 
```
root@server017:~# storj -u http://server016.storj.dk:80 get-info                          
Storj bridge: http://server016.storj.dk:80

Title:       Storj Bridge
Description: Access the Storj network using a simple REST API.
Version:     5.17.1
Host:        109.232.77.16
Protocol:    1.1.0-Th3van-Test
```

//Th3Van

**Comment by braydonf** [comment]
We use `STORJ_BRIDGE=http://localhost:8080 storj get-info` all the time during testing without issue.

**Comment by onsightit** [comment]
Thanks, for the work-around. I've been struggling through the setup of a testnet. When I upload via cli, I get connection refused for 127.0.0.1:8080 in the bridge log. The only thing I can find in the code for a service listening on 8080 is complex.  I tried setting up complex, but it complains about the complex private keys. Any idea how to generate those keys? Or is the issue something else?  Is Complex required?

Thanks

**Comment by braydonf** [comment]
@onsightit The port 8080 I was referencing was from https://github.com/storj/integration
