### ISSUE TITLE
Upload failure: Unable to decode hex string

### ISSUE THREAD

**Issue by StorjNewb** [Storj/libstorj#352]
> $ ./storj upload-file 'Test Data Bucket' ./testfile
>Preparing File...
>Upload failure: Unable to decode hex string

Fresh install of Libstorj 1.0.0-rc7 on Mac OS X Sierra (10.12.5) provides this enormously vague and entirely unhelpful error message with no Indication of where the issue is, or how to resolve it.

**Comment by braydonf** [comment]
The command is: `./storj upload-file <bucket-id> ./testfile`

**Comment by StorjNewb** [comment]
The message should indicate more precisely the issue, or the online help should specify the format of the <bucket-id>.
