### ISSUE TITLE
c99

### ISSUE THREAD

**Issue by cqswxj2013** [Storj/libstorj#355]
Making all in src
make[1]: Entering directory '/home/chen/git_pro/libstorj/src'
/bin/bash ../libtool  --tag=CC   --mode=compile gcc -DPACKAGE_NAME=\"libstorj\" -DPACKAGE_TARNAME=\"libstorj\" -DPACKAGE_VERSION=\"1.0.0\" -DPACKAGE_STRING=\"libstorj\ 1.0.0\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"libstorj\" -DVERSION=\"1.0.0\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_CURL_CURL_H=1 -DHAVE_NETTLE_AES_H=1 -DHAVE_JSON_C_JSON_H=1 -DHAVE_UV_H=1 -DHAVE_MICROHTTPD_H=1 -DHAVE_ALIGNED_ALLOC=1 -DHAVE_POSIX_MEMALIGN=1 -DHAVE_POSIX_FALLOCATE=1 -I.     -g -O2 -O3 -MT storj.lo -MD -MP -MF .deps/storj.Tpo -c -o storj.lo storj.c
libtool: compile:  gcc -DPACKAGE_NAME=\"libstorj\" -DPACKAGE_TARNAME=\"libstorj\" -DPACKAGE_VERSION=\"1.0.0\" "-DPACKAGE_STRING=\"libstorj 1.0.0\"" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"libstorj\" -DVERSION=\"1.0.0\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_CURL_CURL_H=1 -DHAVE_NETTLE_AES_H=1 -DHAVE_JSON_C_JSON_H=1 -DHAVE_UV_H=1 -DHAVE_MICROHTTPD_H=1 -DHAVE_ALIGNED_ALLOC=1 -DHAVE_POSIX_MEMALIGN=1 -DHAVE_POSIX_FALLOCATE=1 -I. -g -O2 -O3 -MT storj.lo -MD -MP -MF .deps/storj.Tpo -c storj.c  -fPIC -DPIC -o .libs/storj.o
storj.c: 在函数‘get_buckets_request_worker’中:
storj.c:135:5: 错误： 只允许在 C99 模式下使用‘for’循环初始化声明
storj.c:135:5: 附注： 使用 -std=c99 或 -std=gnu99 来编译您的代码
storj.c: 在函数‘list_files_request_worker’中:
storj.c:221:5: 错误： 只允许在 C99 模式下使用‘for’循环初始化声明
storj.c: 在函数‘storj_init_env’中:
storj.c:528:18: 警告： 赋值时将整数赋给指针，未作类型转换 [默认启用]
storj.c:582:22: 警告： 赋值时将整数赋给指针，未作类型转换 [默认启用]
storj.c: 在函数‘storj_free_get_buckets_request’中:
storj.c:1089:9: 错误： 只允许在 C99 模式下使用‘for’循环初始化声明
storj.c: 在函数‘storj_free_list_files_request’中:
storj.c:1191:9: 错误： 只允许在 C99 模式下使用‘for’循环初始化声明
Makefile:515: recipe for target 'storj.lo' failed
make[1]: *** [storj.lo] Error 1
make[1]: Leaving directory '/home/chen/git_pro/libstorj/src'
Makefile:455: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

chen@chen-thinkstation:~/git_pro$ gcc -v
使用内建 specs。
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.7/lto-wrapper
目标：x86_64-linux-gnu
配置为：../src/configure -v --with-pkgversion='Ubuntu/Linaro 4.7.4-3ubuntu12' --with-bugurl=file:///usr/share/doc/gcc-4.7/README.Bugs --enable-languages=c,c++,go,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.7 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.7 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-gnu-unique-object --disable-libmudflap --enable-plugin --with-system-zlib --enable-objc-gc --with-cloog --enable-cloog-backend=ppl --disable-cloog-version-check --disable-ppl-version-check --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
线程模型：posix
gcc 版本 4.7.4 (Ubuntu/Linaro 4.7.4-3ubuntu12)

how to add -std=c99 , where to add, vim MAKEFILE DEFS ?

**Comment by braydonf** [comment]
`CFLAGS="-std=gnu99" ./configure`
