### ISSUE TITLE
libstorj/bin/storj downloads corrupt files

### ISSUE THREAD

**Issue by Hapto** [Storj/libstorj#369]
Attempts to download existing files using libstorj/bin/storj results in corrupted files. The node JS storj-lib functions as expected.

A test, today, uploading from the nodejs storj utility, then downloading with libstorj/bin/storj  utility succeeded without problem.

**Comment by braydonf** [comment]
nodejs cli is deprecated, there may be issues and incompatibilities there as it does not implement SIP5. You should be able to download older files with libstorj however.

**Comment by Hapto** [comment]
Quite the opposite. I can download usable files  with the node JS APIs (deprecated), but not with libstorj/bin/storj. What's more, libstorj/bin/storj fils to run on a large number of Linux systems due to building libstorj with gcc libraries newer than those used in many Linux distributions.

**Comment by braydonf** [comment]
Perhaps the incorrect encryption key is being used.
