### ISSUE TITLE
Wrong error code if new bucket name already exists

### ISSUE THREAD

**Issue by kaloyan-raev** [Storj/libstorj#384]
If you try to create new bucket with name that already exists, you'll get the following error:
```
Request failed with status code: 500
```
Error 500 means "Internal Server Error" and is obviously wrong. Duplicated bucket name is something that users can fix on their own. Also, error 500 is too generic and client apps cannot rely on it to display an adequate error.

This seems to be a problem on the bridge server. However, I am opening it here, because there is an issue in libstorj too. Libstorj CLI expects error 404 Not Found if the new bucket name already exists: https://github.com/Storj/libstorj/blob/bf25e2df84a7269472efc0d703000b7207b7fc50/src/cli.c#L924-L925

Error 404 Not Found is semantically wrong for this case too. Perhaps, it's better to return 409 Conflict as discussed here: https://stackoverflow.com/questions/3825990/http-response-code-for-post-when-resource-already-exists

**Comment by braydonf** [comment]
Related issue for bridge: https://github.com/Storj/bridge/issues/322
