### ISSUE TITLE
Uploading many files to one bucket results in timeouts.

### ISSUE THREAD

**Issue by tempestb** [Storj/libstorj#392]
This is a well known problem, but I didn't find an issue for it here, so I thought I would add it in.

I think this is probably the biggest handicap to the working upload process.  When you reach a certain number of files in a bucket, you can no longer upload.  Especially with FileZilla which attempts to do a DIR on the folder before it uploads and will fail endlessly.   

This has a few negatives...

A)  It's tying up processes on the bridge to try and return these results.  (Speculation)

B)  It's frustrating to the end user.

C)  It looks bad for Storj to be unable to do something everyone else has been doing since DOS was released for the 8088.

  We can make recommendations to zip up many files and everything.  But users just want to drag and drop a big folder full of photos or perhaps a git/subversion repository and let the system handle it.  Being blocked from doing this is not good for the Storj experience.

Once the urgent issues are crushed, I think this should move to the top of the list to fix or workaround.  I think it's most important to make the experience for the client-renter to have a seamless experience with Storj however possible.  

Thanks!
Kevin

**Comment by braydonf** [comment]
LIkely duplicate https://github.com/Storj/libstorj/issues/363

**Comment by braydonf** [comment]
As well as https://github.com/Storj/sips/issues/19
