### ISSUE TITLE
Upload failure: Farmer request error

### ISSUE THREAD

**Issue by utdrmac** [storj/libstorj#396]
Have repeatedly attempted to upload simple 150MB movie. Repeated failures.
[storj_log.txt](https://github.com/Storj/libstorj/files/1412495/storj_log.txt)

**Comment by falconict** [comment]
I have received the same failure with a 28MB file, the first I attempted to transfer.  I'm using libstorj-2.0.0-beta-linux64.tar.gz as the archive for the libstorj 2.0.0. binary.  I have a NAT network with open outgoing TCP ports

[farmer_request_error_log.txt](https://github.com/Storj/libstorj/files/1452637/farmer_request_error_log.txt)

**Comment by utdrmac** [comment]
I tried uploading a 10MB file. That worked. Tried a 15MB. That failed. Tried 20MB. That failed.
Helene Unland, storj community person, said to me that my internet speed probably isn't fast enough which is complete bullsh*t. If storj cannot handle **ANY** upload speeds, it's not worth it and is not a very robust system.

**Comment by braydonf** [comment]
Both of these logs have many repeated timeout failures when sending shards to farmers. More information is needed to known why those transfers are repeatedly failing.

**Comment by utdrmac** [comment]
@braydonf What more info would you like?

**Comment by braydonf** [comment]
Need to identify why every shard upload is timing out, there could be various reasons.

**Comment by utdrmac** [comment]
Let me know what I need to type/run.

**Comment by braydonf** [comment]
There could be various reasons that would cause the timeout:
1) Very slow speed connection that is triggering the slow farmer detection to cancel and try a faster farmer, setting the LOW_SPEED_LIMIT could be used to configure this this https://github.com/Storj/libstorj/blob/master/src/cli.c#L1153
2) Non-standard ports are being blocked by network, checking that this isn't the case or a firewall isn't enabled. Using the proxy settings could also work around any firewall issues, see: https://github.com/Storj/libstorj/blob/master/src/cli.c#L58
3) Being extremely unlucky and getting a truly bad set of farmers that don't accept data, updates to reputation metric in SIP9 should cover this case, if it were to become an issue: https://github.com/Storj/bridge/pull/521

**Comment by MeijeSibbel** [comment]
@braydonf , i am seeing this issue repeatedly when uploading 1 byte files with libstorj. Everything above 1 byte uploads fine. We use 1 byte files for uploading directory structure info to Storj. 

```
Sleeping for 1 minute...
Checking for changes...
Sleeping for 1 minute...
3 seconds after the last file event
Sleep interrupted
Checking for changes...
3 seconds after the last file event
Creating cloud directory Stardock/...
    0%               0/0 bytes
  100%               1/1 bytes
  Upload failed. Farmer request error (2000)
Creating cloud directory Stardock - Copy/...
    0%               0/0 bytes
  100%               1/1 bytes
  done.
Creating cloud directory Stardock - Copy (2)/...
    0%               0/0 bytes
  100%               1/1 bytes
  Upload failed. Farmer request error (2000)
Creating cloud directory Stardock - Copy (3)/...
    0%               0/0 bytes
  100%               1/1 bytes
  Upload failed. Farmer request error (2000)
Checking for changes...
```

https://github.com/GooBox/goobox-sync-storj/issues/69

**Comment by braydonf** [comment]
Thanks for that info @MeijeSibbel

**Comment by MeijeSibbel** [comment]
some filezilla debug info:

```
Trace:	Pending work count: 1
Trace:	Pushing frame for shard index 0... (retry: 0)
Trace:	fn[push_frame] - JSON body: { "hash": "69d7ef8f42a25e8791bb37d5fb48456f102a3cb9", "size": 1, "index": 0, "parity": false, "challenges": [ "31e7989a90628843a2c21d4d5074edc18b38c08c248746f9cf66df2dfe871130", "6415cc372bcd298678aaf69f2ca715d9a0e8dcc8e2de120e1aff93ed2d85abc6", "c8921fc4637fe7b15bfc31c324f8ef1b79f95e654cadb5c5f20d6fdc253b303d", "19c056e062cf4bee3ebc3a55860bf6efe3f56aec327b0eeb8c821fded9afdcf8" ], "tree": [ "5328bca39cd488964732ae87a8136366e4c98621", "6c94a13919aba41c388be4211d44364b4db050ea", "d2bfcf0966f350b431b8e4e5e3aef335cac69695", "7da059634a85afcd085d9c3883ee1d05c0ee7746" ], "exclude": [ "1ad47e9b74c68702e29abd4381eb343e5307ee7f", "1ad2446a7c3ead7e9013357367787e9777a9d15c", "63d6d3f2d3204299094100beac0556e967ed091f", "63faefac836010d47490faeebfcb02494f6e6c19", "63da70ff692cdb7703e04f08fb627e8ed166b66e", "63eb7fde6fa76eca65d5f688c60298259c1064df" ] }
Trace:	fn[push_frame] - JSON Response: { "hash": "69d7ef8f42a25e8791bb37d5fb48456f102a3cb9", "token": "1b892a0da83e5cbb43f44478c4b69235c9e41415", "operation": "PUSH", "farmer": { "userAgent": "8.5.0", "protocol": "1.2.0", "address": "bobino.ddns.net", "port": 4003, "nodeID": "1ad129fe215b272dcbce87af031555c03d3f0914", "lastSeen": "2018-01-13T11:52:04.850Z" } }
Trace:	Contract negotiated with: { "userAgent: "8.5.0", "protocol:" "1.2.0", "port": "4003", "nodeID": "1ad129fe215b272dcbce87af031555c03d3f0914"}
Trace:	Pending work count: 1
Trace:	Transfering Shard index 0... (retry: 6)
Trace:	Put shard request error code: 7
Trace:	Failed to push shard 0
Trace:	fn[cleanup_state] - Cleaning up shard 0
Trace:	fn[cleanup_state] - Cleaning up pointers 0
Error:	Upload failed with error Farmer request error (2000)
Trace:	CStorjMkdirOpData::ParseResponse() in state 3
Trace:	CStorjControlSocket::ResetOperation(2)
Trace:	CControlSocket::ResetOperation(2)
Trace:	CFileZillaEnginePrivate::ResetOperation(2)
```

Looks like it retries 6x and then fails.

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
