### ISSUE TITLE
Frame isn't deleted after deleting the associated file

### ISSUE THREAD

**Issue by jkawamoto** [Storj/libstorj#399]
[remove-file command](https://github.com/Storj/libstorj/blob/master/src/cli.c#L1432) looks not deleting the associated frame. I’m wondering if it is expected behavior because no functions call [storj_bridge_delete_frame](https://github.com/Storj/libstorj/blob/master/src/storj.c#L1435).

**Comment by braydonf** [comment]
Deleting the frame isn't expected.

**Comment by jkawamoto** [comment]
I thought a frame represents an uploaded file and has a set of pointers to shards, and a file represents metadata including a pointer to a frame. So, if a file is deleted, shards are still stored in farmers until the associated frame is deleted. Is my understanding correct?

**Comment by braydonf** [comment]
Yeah, there is some work necessary to free disk space before the contracts expire which will clean it up currently.

**Comment by jkawamoto** [comment]
I see. So currently, we cannot delete actual files until contracts will be expired.

**Comment by braydonf** [comment]
Yeah, that's something being looked at, discussed a bit in the meeting just earlier: https://github.com/Storj/dev-meetings/blob/master/2017-11-08-summary.md
