### ISSUE TITLE
Add pre-encryption block level dedupe and compression to minimize storage requirements

### ISSUE THREAD

**Issue by eharris** [storj/libstorj#421]
So far I have been unable to find any ability (or documentation regarding) doing cross-file block level de-dupe and compression, which would have to be done prior to encryption.

This is really a requirement for large libraries of virtual machine disk images where only a small amount of each image is different.  It would also be useful to minimize wasted space, bandwidth, and consequently storage fees for things like point-in-time backups of large append-only log files, slowly changing database files, etc.

**Comment by braydonf** [comment]
I think this falls out side of the scope of this library. There are many different ways to compress data, and can be done prior to transferring files.

**Comment by tempestb** [comment]
You would have to manage that on the client end before sending to Storj.  Storj data is encrypted as you mentioned, and so none of the data in the network can be analyzed by anyone except the client who uploaded the data, after it is decrypted at the client.

**Comment by braydonf** [comment]
An example:
```
tar -cvzf logs/* logs.tar.gz && storj upload-file <bucket-id> ./logs.tar.gz
```

**Comment by eharris** [comment]
Compression is actually a lesser concern, the block dedupe is really much more valuable.  While there are easy tools to do compression, there aren't easy tools to do block dedupe, and since this would (obviously) have to be done before compression, the storage library is the obvious place for it to be done.

**Comment by tempestb** [comment]
It can't be done.  The data is encrypted and split into shards and distributed around the world.  You would have to reassemble it, decrypt it, and then run your comparison.  You could certainly do this at the client and then upload only your changes, but the library itself is not able to do this to files that have been uploaded.

**Comment by eharris** [comment]
I think I made it very clear, I'm saying it HAS to be done before the file is sharded and encrypted.  It would be asinine to try to do it after the fact.

**Comment by tempestb** [comment]
@eharris Right, so you can write an application to do this.  It's not something the libstorj library would be used for.  Libstorj isn't a block level compare utility.  It's for uploading and downloading and managing your data on the Storj network.

**Comment by eharris** [comment]
It seems like it would be perfect for it to be included in libstorj, since there are many other deduplicating storage engines already on the market.  Or does storj WANT to be lagging in features?

Just for reference: https://dzone.com/articles/why-deduplication-matters-for-cloud-storage

**Comment by tempestb** [comment]
@eharris I think you're misunderstanding the purpose of the application.  libstorj is a library for working with the data.  It's meant for developers to integrate Storj into their projects and development.  If you want to write such a tool and market it, you can use Storj as your backend.  But Storj Labs isn't looking to recreate all the existing applications out there and compete against them.  They are building a low cost backend so the developers of these tools can choose them over more expensive and less secure packages.  It would be up to the Dropbox's and oDrive's of the world to integrate these features you are asking for.

**Comment by braydonf** [comment]
IMO, this is a task better suited for a suite of compression tools, rather than implementing something that has limited capabilities. e.g. the unix philosophy of doing one thing and doing it well. And then combining tools for more sophisticated and composable functionality.

**Comment by eharris** [comment]
libstorj takes files and directories, and does all the processing necessary (sharding, key management, encryption, uploading, etc).  Doing the additional level of allowing for deduplication *could* be done in a separate application, but then it isn't cross platform and intrinsic to the platform (what about on my phone?).   And it means libstorj doesn't provide a major feature that is becoming increasingly important for managing ever-increasing storage needs.

Dropbox, wuala, Memopal, JustCloud, and Mozy are just a few examples of cloud storage systems that use data deduplication techniques at a source (i.e. client side) to save network bandwidth from a user to cloud servers as well as storage requirements.  They don't require a separate add-on application in front of their service to give users the benefit of de-duplication.

Yes, storj gives other features (strong E2E encryption) that some others don't, but do we want storj to be missing a major feature that other big providers *do* provide?  Isn't storj trying to compete with those other providers by offering an better service?

**Comment by tempestb** [comment]
No.  Storj is the backend that services such as Dropbox, Wuala, Memopal, JustCloud and Mozy can adopt for their software packages.

**Comment by braydonf** [comment]
Hmmm... Cross platform development and compatibility could be a reason to support built-in compression that could be supported wherever libstorj is supported, minimizing developer requirements to do this beforehand. If built-in support for compression was added, it should be optional. Databases such as LevelDB support snappy for compression, however in my experience, those features of LevelDB are not often used because data is already encrypted or obfuscated before it reaches that step.

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
